### ISSUE TITLE
Missing dependencies for myBinder

### ISSUE THREAD

**Issue by stain** [ImranAsif48/RO2019#2]
Launching in myBinder works, but it fails immediately as `seaborn` is not installed. See https://mybinder.readthedocs.io/en/latest/using.html#preparing-a-repository-for-binder on how to add `pip` dependencies

In addition some of the later commands don't work as some files are in `zip` format in GitHub, perhaps add `!unzip FOO.zip` etc. to ensure the CSV files can be loaded by myBinder.

**Comment by ImranAsif48** [comment]
Thanks @stain for raising this issue. I am working on it. I will update soon

**Comment by ImranAsif48** [comment]
Issue has been resolved. Thanks @stain
